### ISSUE TITLE
language not changing

### ISSUE THREAD

**Issue by Zeeck420** [Noisyfox/ACT.FFXIVPing#11]
language will not change to English

**Comment by Noisyfox** [comment]
Make sure the en-US folder is placed correctly.
Check the doc here https://github.com/Noisyfox/ACT.FFXIVTranslate/wiki/How-to-Install-&-Change-Plugin-Language

**Comment by Zeeck420** [comment]
ok thank you, I told me not to put it there so I wasn't sure. thank you for the help.
