### ISSUE TITLE
求问大佬还会更新修复吗？

### ISSUE THREAD

**Issue by sao321** [Noisyfox/ACT.FFXIVPing#19]
大佬这个根据tick rate的方案，测通过VPN连服务器时比目前其它所有的方案都准确，可惜没有其它插件作者采用。

大佬貌似很久没更新了，目前显示

`[Warn] Deucalion not detected for process 19420, plugin may not working properly`

ping测出来为0或者1，求问大佬还能抽空修一修吗？

万分感谢

**Comment by Noisyfox** [comment]
会修，但是要等下个月

**Comment by Noisyfox** [comment]
https://ci.appveyor.com/project/Noisyfox/act-ffxivping/branch/master/job/rgab0ood3e94fdvo/artifacts
试一下这个版本呢
