### ISSUE TITLE
在腾讯或者玲珑加速器下似乎无法正常获取延迟

### ISSUE THREAD

**Issue by SwordSing** [Noisyfox/ACT.FFXIVPing#4]
在腾讯或者玲珑加速器下似乎无法正常获取延迟，有什么办法可以避免这种情况么？谢谢！

**Comment by Noisyfox** [comment]
你开了高级模式吗

**Comment by SwordSing** [comment]
> 你开了高级模式吗

是开了高级模式的  但是显示的延迟应该也不对 跟资源管理器里显示的一直

**Comment by Noisyfox** [comment]
玲珑的话试试看去设置里启用备用模式。

**Comment by SwordSing** [comment]
数值偏小 开不开高级模式显示的是一样的数值

**Comment by Noisyfox** [comment]
你试过加速器的各种备用模式没？另外你ACT有没有添加到防火墙排除里？

**Comment by SwordSing** [comment]
act是正常的 用uu加速或者提莫苑都可以正常工作

**Comment by Noisyfox** [comment]
你act的解析模式用的什么

**Comment by itholl** [comment]
国服延迟显示正常，国际服延迟有点不正常，请问这种是因为加速器的问题吗

**Comment by Noisyfox** [comment]
@itholl 你用的什么加速器
