### ISSUE TITLE
请问全新的原版ACT加载插件就报错该怎么解决_(:з」∠)_

### ISSUE THREAD

**Issue by CelestialEclispe** [Noisyfox/ACT.FFXIVPing#5]
请问全新的原版ACT加载插件就报错该怎么解决_(:з」∠)_
一加载就提示Init failed before settings are loaded. Settings won't be saved until next successfully initialization to prevent settings lost!
Caused by:
System.Xml.XmlException:缺少根元素。
在 System.Xml.XmlTextReaderlmpl.Throw(Exception e)
在 System.Xml.XmlTextReaderlmpl.ParseDocumentContent()
在 ACT.FFXIVPing.PluginSettings.Load()
在 ACT.FFXIVPing.FFXIVPingPlugin.lnitPlugin(TabPage pluginScreenSpace, Label pluginStatusText)

**Comment by Noisyfox** [comment]
删掉 "C:\Users\<user name>\AppData\Roaming\Advanced Combat Tracker\Config\ACT.FFXIVPing.config.xml" 再开
