### ISSUE TITLE
在有加速器的环境下无法正常工作

### ISSUE THREAD

**Issue by Zeeroz** [Noisyfox/ACT.FFXIVPing#6]
使用的是UU加速器，加速FF14只有模式三和模式四可选取
（解析插件winpcap模式，ping插件高级模式已开）
在模式三状态下延迟显示0
在模式四状态下显示个位数延迟

**Comment by Zeeroz** [comment]
已更新至1.3.0.51，问题依旧存在

**Comment by Zeeroz** [comment]
1.4.1问题照旧
![image](https://user-images.githubusercontent.com/38998206/74031468-8cb4f380-49ec-11ea-9d26-f2fb9b798dfe.png)

**Comment by Noisyfox** [comment]
延迟不是对的吗

**Comment by Noisyfox** [comment]
我试了一下，UU的延迟就是比实际的延迟高。我对比了抓包的结果，游戏的ping包的rtt和我的插件是一致的，不知道UU的延迟是怎么计算的。

**Comment by Noisyfox** [comment]
![TIM截图20200208001043](https://user-images.githubusercontent.com/1537155/74033157-a9135900-4a09-11ea-9948-3c7e0ea2fd7f.png)
![TIM截图20200208001213](https://user-images.githubusercontent.com/1537155/74033163-aa448600-4a09-11ea-8f9a-e9aec66f8cdd.png)
模式三和模式四数据都是正常的。

**Comment by Zeeroz** [comment]
> 延迟不是对的吗

看我第一张图的右上角，延迟7ms
明显不对啊

**Comment by Noisyfox** [comment]
![image](https://user-images.githubusercontent.com/1537155/74035668-c991e200-4a0e-11ea-8a0a-4d0da3fd4c0d.png)
好的呀emmmm同样的节点

**Comment by Zeeroz** [comment]
是我这边环境的问题么。。
之前可以正常使用的，但是从某个时间开始就断断续续无法工作了
包括那个翻译插件（https://github.com/Noisyfox/ACT.FFXIVTranslate）

我刚刚重启了电脑，然后重新开ACT和FF14，问题还是没有解决。。

**Comment by Noisyfox** [comment]
你修复下LSP试试

**Comment by Zeeroz** [comment]
修复LSP无效

然后尝试windows控制面板重置网络也无效
就很奇怪

**Comment by Zeeroz** [comment]
尝试使用手机流量连入网络，然后ping可以检测到40~80之间跳动
感觉是ping到了加速器的入口？

**Comment by Noisyfox** [comment]
那你FFXIV解析插件用网络模式可以工作吗？还是必须要用winpcap？

**Comment by Zeeroz** [comment]
网络模式没有数据，只能用winpcap

**Comment by Noisyfox** [comment]
那我知道了，我的插件也需要切换到pcap模式才能读到，可能是你环境的某些设置问题，比如防火墙之类的。

**Comment by Zeeroz** [comment]
> 那我知道了，我的插件也需要切换到pcap模式才能读到，可能是你环境的某些设置问题，比如防火墙之类的。我近期会尝试加一个解析模式选项看看。

感谢大佬
翻译插件那边应该也是同样的问题，也是解析不到游戏内的文本内容。希望能一并加上这个功能

**Comment by Noisyfox** [comment]
https://ci.appveyor.com/project/Noisyfox/act-ffxivping/builds/30649480/job/hb0dna7sfdoamy8y/artifacts

试一下这个版本

**Comment by Zeeroz** [comment]
> https://ci.appveyor.com/project/Noisyfox/act-ffxivping/builds/30649480/job/hb0dna7sfdoamy8y/artifacts
> 
> 试一下这个版本

![image](https://user-images.githubusercontent.com/38998206/74081189-0994ab80-4a87-11ea-84ac-553d72e1065d.png)

没用。。
