### ISSUE TITLE
new update crash 

### ISSUE THREAD

**Issue by patsy158** [Noisyfox/ACT.FFXIVPing#7]
caused fatal error
---------------------------
Fatal Error - Unhandled Exception
---------------------------
An unhandled exception has occurred.  ACT may close.
Press Ctrl-C to copy this MessageBox.

System.TypeInitializationException - The type initializer for 'Machina.FFXIV.Headers.Opcodes.OpcodeManager' threw an exception.
   at Machina.FFXIV.FFXIVNetworkMonitor.Start()

   at ACT.FFXIVPing.MachinaProbeService.<>c.<ControllerOnGameProcessUpdated>b__5_0(UInt32 _pid)

   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)

   at ACT.FFXIVPing.MachinaProbeService.ControllerOnGameProcessUpdated(Boolean fromView, HashSet`1 pids)

   at ACT.FoxCommon.core.MainControllerBase.OnGameProcessUpdated.Invoke(Boolean fromView, HashSet`1 pids)

   at ACT.FFXIVPing.GameProcessMonitor.MonitorThread.DoWork(MainController context)

   at ACT.FoxCommon.core.BaseThreading`1.WorkingThreadFunc(Object context)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Machina.FFXIV.FFXIVNetworkMonitor, ACT.FFXIVPing, Version=1.4.0.56, Culture=neutral, PublicKeyToken=null
---------------------------
OK   
---------------------------

**Comment by yjywybb** [comment]
相同报错，在点开高级检测模式后发生

**Comment by Zeeroz** [comment]
1.4版本，同样报错。只要加载插件就报错
---------------------------
Fatal Error - Unhandled Exception
---------------------------
An unhandled exception has occurred.  ACT may close.
Press Ctrl-C to copy this MessageBox.

System.TypeInitializationException - “Machina.FFXIV.Headers.Opcodes.OpcodeManager”的类型初始值设定项引发异常。
   在 Machina.FFXIV.FFXIVNetworkMonitor.Start()

   在 ACT.FFXIVPing.MachinaProbeService.<>c.<ControllerOnGameProcessUpdated>b__5_0(UInt32 _pid)

   在 System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)

   在 ACT.FFXIVPing.MachinaProbeService.ControllerOnGameProcessUpdated(Boolean fromView, HashSet`1 pids)

   在 ACT.FoxCommon.core.MainControllerBase.OnGameProcessUpdated.Invoke(Boolean fromView, HashSet`1 pids)

   在 ACT.FFXIVPing.GameProcessMonitor.MonitorThread.DoWork(MainController context)

   在 ACT.FoxCommon.core.BaseThreading`1.WorkingThreadFunc(Object context)

   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   在 System.Threading.ThreadHelper.ThreadStart(Object obj)

Machina.FFXIV.FFXIVNetworkMonitor, ACT.FFXIVPing, Version=1.4.0.56, Culture=neutral, PublicKeyToken=null
---------------------------
确定   
---------------------------

**Comment by yjywybb** [comment]
> ## 1.4版本，同样报错。只要加载插件就报错
> ## Fatal Error - Unhandled Exception
> An unhandled exception has occurred. ACT may close.
> Press Ctrl-C to copy this MessageBox.
> 
> System.TypeInitializationException - “Machina.FFXIV.Headers.Opcodes.OpcodeManager”的类型初始值设定项引发异常。
> 在 Machina.FFXIV.FFXIVNetworkMonitor.Start()
> 
> 在 ACT.FFXIVPing.MachinaProbeService.<>c.b__5_0(UInt32 _pid)
> 
> 在 System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
> 
> 在 ACT.FFXIVPing.MachinaProbeService.ControllerOnGameProcessUpdated(Boolean fromView, HashSet`1 pids)
> 
> 在 ACT.FoxCommon.core.MainControllerBase.OnGameProcessUpdated.Invoke(Boolean fromView, HashSet`1 pids)
> 
> 在 ACT.FFXIVPing.GameProcessMonitor.MonitorThread.DoWork(MainController context)
> 
> 在 ACT.FoxCommon.core.BaseThreading`1.WorkingThreadFunc(Object context)
> 
> 在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> 
> 在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> 
> 在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
> 
> 在 System.Threading.ThreadHelper.ThreadStart(Object obj)
> 
> ## Machina.FFXIV.FFXIVNetworkMonitor, ACT.FFXIVPing, Version=1.4.0.56, Culture=neutral, PublicKeyToken=null
> ## 确定

加载就报错可能是旧版默认勾了高级检测的原因？可以手动修改配置文件或者干脆直接删了让它重新生成一个
位置：%appdata%\Advanced Combat Tracker\Config\\ACT.FFXIVPing.config.xml
checkBoxAdvancedPing改成False

**Comment by Zeeroz** [comment]
> > ## 1.4版本，同样报错。只要加载插件就报错
> > ## Fatal Error - Unhandled Exception
> > An unhandled exception has occurred. ACT may close.
> > Press Ctrl-C to copy this MessageBox.
> > System.TypeInitializationException - “Machina.FFXIV.Headers.Opcodes.OpcodeManager”的类型初始值设定项引发异常。
> > 在 Machina.FFXIV.FFXIVNetworkMonitor.Start()
> > 在 ACT.FFXIVPing.MachinaProbeService.<>c.b__5_0(UInt32 _pid)
> > 在 System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
> > 在 ACT.FFXIVPing.MachinaProbeService.ControllerOnGameProcessUpdated(Boolean fromView, HashSet`1 pids)
> > 在 ACT.FoxCommon.core.MainControllerBase.OnGameProcessUpdated.Invoke(Boolean fromView, HashSet`1 pids)
> > 在 ACT.FFXIVPing.GameProcessMonitor.MonitorThread.DoWork(MainController context)
> > 在 ACT.FoxCommon.core.BaseThreading`1.WorkingThreadFunc(Object context)
> > 在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> > 在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> > 在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
> > 在 System.Threading.ThreadHelper.ThreadStart(Object obj)
> > ## Machina.FFXIV.FFXIVNetworkMonitor, ACT.FFXIVPing, Version=1.4.0.56, Culture=neutral, PublicKeyToken=null
> > ## 确定
> 
> 加载就报错可能是旧版默认勾了高级检测的原因？可以手动修改配置文件或者干脆直接删了让它重新生成一个
> 位置：%appdata%\Advanced Combat Tracker\Config\ACT.FFXIVPing.config.xml
> checkBoxAdvancedPing改成False

改完配置文件以后可以用普通模式了，虽然延迟依旧不对

**Comment by Noisyfox** [comment]
请尝试一下这个版本
https://ci.appveyor.com/project/Noisyfox/act-ffxivping/build/job/h1v03b3tcha4s61j/artifacts

下载链接里第一个 ACT.FFXIVPing.dll 文件替换原来的插件。

**Comment by Noisyfox** [comment]
https://github.com/Noisyfox/ACT.FFXIVPing/releases/tag/1.4.1 已发布
